language: android

sudo: false

android:
  components:
  - build-tools-25.0.1
  - android-23
  - extra-android-m2repository
  - extra-android-support

before_install:
    - yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2"
    - yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2"

script:
  - chmod +x gradlew
  - ./gradlew assembleRelease
