language: android

sudo: false

android:
  components:
  - build-tools-25.0.1
  - android-23
  - extra-android-m2repository
  - extra-android-support

script:
  - chmod +x gradlew
  - ./gradlew assembleRelease
